# Generated by Django 5.2.17 on 2026-09-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConformityCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minion_id", models.CharField(max_length=128, unique=True)),
                ("source_jid", models.CharField(max_length=255)),
                ("verdict", models.BooleanField(null=True)),
                ("highstate_jid", models.CharField(blank=True, max_length=255)),
                ("highstate_time", models.DateTimeField(blank=True, null=True)),
                ("computed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alcali_conformity_cache",
            },
        ),
    ]
