# Generated by Django 5.2.17 on 2026-09-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_conformitycache"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beacon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minion", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("config", models.TextField()),
            ],
        ),
    ]
