# Generated by Django 5.2.17 on 2026-09-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_beacon"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("conformity", "A minion's last highstate did not pass"),
                            ("silent", "A minion has not returned anything lately"),
                        ],
                        default="conformity",
                        max_length=32,
                    ),
                ),
                ("threshold_days", models.PositiveIntegerField(default=1)),
                ("webhook_url", models.CharField(blank=True, max_length=500)),
                ("email_to", models.CharField(blank=True, max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="NotificationState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minion_id", models.CharField(max_length=128)),
                ("state", models.CharField(default="clear", max_length=16)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="api.notificationrule",
                    ),
                ),
            ],
            options={
                "unique_together": {("rule", "minion_id")},
            },
        ),
    ]
