# Generated by Django 5.2.17 on 2026-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notificationrule_notificationstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='minion',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='keys',
            name='minion_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='minions',
            name='minion_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='minion',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
